name: CI/CD 

on:
  push:
    branches:
      - '*'


jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Repository
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.3

      - name: Run Tests
        run: make test

      - name: Merge to Main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: git merge &{{ github.event_before }}
