name: CI/CD 

on:
  push:
    branches:
      - '*'


jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.3 

      - name: Run Tests
        run: make test

      - name: Merge to Main
        if: github.ref != 'refs/heads/main' && github.base_ref == 'refs/heads/main'
        run: git merge origin/$\{\{ github\.base\_ref \}\}\